config/routes.rb
Rails.application.routes.draw do
  resources :user_profiles
  resources :applists
  resources :rewards
  resources :points
  resources :withdrawls
  # resources :transactions
  resources :accounts
  resources :appopens
  resources :users
  resources :game_points
  resources :tasks
  resources :news
  resources :matches
  resources :players
  resources :teams

  mount Matchlist => '/'
  mount Previewlist => '/'
  mount Playerlist => '/'
  mount Tasklist => '/'
  mount Signup => '/'
  mount Apopen => '/'
  mount Appinvite => '/'
  mount RewardList => '/'
  mount WithdrawlCreate => '/'
  mount WithdrawlHistory => '/'
  mount Gameplay => '/'
  mount Topfantasyapps => '/'
  mount Spintask => '/'
  mount EarnHistory => '/'
  mount Profilelist => '/'

  root "matches#index"

  get "dashboard/index"

  get "players", to: "teams#players"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :withdrawls, dependent: :destroy
  has_many :points, dependent: :destroy
end

app/models/applist.rb
class Applist < ApplicationRecord
end

app/models/appopen.rb
class Appopen < ApplicationRecord
  belongs_to :user
end

app/models/game_point.rb
class GamePoint < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
end 

app/models/point.rb
class Point < ApplicationRecord
    belongs_to :account
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
    has_many :news
end

app/models/user.rb
class User < ApplicationRecord
    has_many :appopens, dependent: :destroy
    has_one :account, dependent: :destroy
    has_one :user_profile, dependent: :destroy
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/models/withdrawl.rb
class Withdrawl < ApplicationRecord
  belongs_to :account
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: %i[ show edit update destroy ]

  # GET /rewards or /rewards.json
  def index
    @rewards = Reward.all.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /rewards/1 or /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards or /rewards.json
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully created." }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1 or /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully updated." }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1 or /rewards/1.json
  def destroy
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url, notice: "Reward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward_params
      params.require(:reward).permit(:payout_name, :payout_logo, :payout_type, :payout_amount, :coin_value)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward) do |form| %>
  <% if reward.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :payout_name, style: "display: block" %>
    <%= form.text_field :payout_name %>
  </div>

  <div>
    <%= form.label :payout_logo, style: "display: block" %>
    <%= form.text_field :payout_logo %>
  </div>

  <div>
    <%= form.label :payout_type, style: "display: block" %>
    <%= form.text_field :payout_type %>
  </div>

  <div>
    <%= form.label :payout_amount, style: "display: block" %>
    <%= form.text_field :payout_amount %>
  </div>

  <div>
    <%= form.label :coin_value, style: "display: block" %>
    <%= form.text_field :coin_value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/_reward.html.erb
<div id="<%= dom_id reward %>">
  <!-- <p>
    <strong>Payout name:</strong>
    <%= reward.payout_name %>
  </p>

  <p>
    <strong>Payout logo:</strong>
    <%= reward.payout_logo %>
  </p>

  <p>
    <strong>Payout type:</strong>
    <%= reward.payout_type %>
  </p>

  <p>
    <strong>Payout amount:</strong>
    <%= reward.payout_amount %>
  </p>

  <p>
    <strong>Coin value:</strong>
    <%= reward.coin_value %>
  </p> -->
  
  <td><%= reward.payout_name %></td>
  <td><img src="<%= reward.payout_logo %>" style="height:30px"></td>
  <td><%= reward.payout_type %></td>
  <td><%= reward.payout_amount %></td>
  <td><%= reward.coin_value %></td>
          




</div>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render "form", reward: @reward %>

<br>

<div>
  <%= link_to "Show this reward", @reward %> |
  <%= link_to "Back to rewards", rewards_path %>
</div>

app/views/rewards/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Rewards</h1>       
    <%= link_to "New reward", new_reward_path, class:"btn btn-primary", style:"text-align: right;" %>
  </div>
<table class="table table-info table-striped table-hover" style="text-align: center;">
  <thead>
    <tr>
    <th>Name</th>
    <th>Logo</th>
    <th>Payout_Type</th>
    <th>Payout_Amount</th>
    <th>Coin_value</th>
    <th>Show</th>
    </tr>
  </thead>
  <% @rewards.each do |reward| %>
  <tr>
    <%= render reward %>
    <td>
      <%= link_to "Show this reward", reward, class:'btn btn-outline-primary' %>
    </td>
  </tr>
  <% end %>
  </table>
  <div class="d-flex justify-content-between">
    <%= will_paginate @rewards , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <span><%= page_entries_info(@rewards)%></span>
  </div>
</div>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render "form", reward: @reward %>

<br>

<div>
  <%= link_to "Back to rewards", rewards_path %>
</div>

app/views/rewards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reward %>

<div>
  <%= link_to "Edit this reward", edit_reward_path(@reward) %> |
  <%= link_to "Back to rewards", rewards_path %>

  <%= button_to "Destroy this reward", @reward, method: :delete %>
</div>