config/routes.rb
Rails.application.routes.draw do
  resources :user_profiles
  resources :applists
  resources :rewards
  resources :points
  resources :withdrawls
  # resources :transactions
  resources :accounts
  resources :appopens
  resources :users
  resources :game_points
  resources :tasks
  resources :news
  resources :matches
  resources :players
  resources :teams

  mount Matchlist => '/'
  mount Previewlist => '/'
  mount Playerlist => '/'
  mount Tasklist => '/'
  mount Signup => '/'
  mount Apopen => '/'
  mount Appinvite => '/'
  mount RewardList => '/'
  mount WithdrawlCreate => '/'
  mount WithdrawlHistory => '/'
  mount Gameplay => '/'
  mount Topfantasyapps => '/'
  mount Spintask => '/'
  mount EarnHistory => '/'
  mount Profilelist => '/'

  root "matches#index"

  get "dashboard/index"

  get "players", to: "teams#players"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :withdrawls, dependent: :destroy
  has_many :points, dependent: :destroy
end

app/models/applist.rb
class Applist < ApplicationRecord
end

app/models/appopen.rb
class Appopen < ApplicationRecord
  belongs_to :user
end

app/models/game_point.rb
class GamePoint < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
end 

app/models/point.rb
class Point < ApplicationRecord
    belongs_to :account
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
    has_many :news
end

app/models/user.rb
class User < ApplicationRecord
    has_many :appopens, dependent: :destroy
    has_one :account, dependent: :destroy
    has_one :user_profile, dependent: :destroy
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/models/withdrawl.rb
class Withdrawl < ApplicationRecord
  belongs_to :account
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_navbar.html.erb
<div class="container-fluid">
        <nav class="navbar navbar-dark bg-dark bg-gradient fixed-top">
            <div class="container-fluid">
                <%= link_to "CricGuru" , matches_path, class: "navbar-brand ps-3"%>
              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">CricGuru</h5>
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <%= link_to "Users", users_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "User Profile", user_profiles_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Appopen", appopens_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "Accounts", accounts_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Matches", matches_path, class: "nav-link " %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Teams", teams_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Players", players_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                            <%= link_to "News", news_index_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Rewards", rewards_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%>
                        </li>
                        
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                             Transactions
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li><%= link_to "Earnings", points_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%></li>
                            <li><%= link_to "Withdrawls", withdrawls_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%></li>
                            
                        </ul>
                    </li>
                    <li>
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Offers
                       </a>
                        <ul class="dropdown-menu dropdown-menu-dark"> 
                            <li><%= link_to "Task Offers", tasks_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%></li>
                            <li><%= link_to "Game Point", game_points_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%></li>
                            <li><%= link_to "Applists", applists_path, class: "nav-link collapsed sb-nav-link-icon fas fa-columns sb-sidenav-collapse-arrow fas fa-angle-down"%></li>
                      </ul>
                    </li>
                  </ul>
                  <!-- <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                  </form> -->
                </div>
              </div>
            </div>
          </nav>

              <div class="small">Logged in as:</div>
              Start Bootstrap
          </div>
  
  <div id="layoutSidenav_content">
    <main>
        <%= yield %>
    </main>
  </div>