config/routes.rb
Rails.application.routes.draw do
  resources :user_profiles
  resources :applists
  resources :rewards
  resources :points
  resources :withdrawls
  # resources :transactions
  resources :accounts
  resources :appopens
  resources :users
  resources :game_points
  resources :tasks
  resources :news
  resources :matches
  resources :players
  resources :teams

  mount Matchlist => '/'
  mount Previewlist => '/'
  mount Playerlist => '/'
  mount Tasklist => '/'
  mount Signup => '/'
  mount Apopen => '/'
  mount Appinvite => '/'
  mount RewardList => '/'
  mount WithdrawlCreate => '/'
  mount WithdrawlHistory => '/'
  mount Gameplay => '/'
  mount Topfantasyapps => '/'
  mount Spintask => '/'
  mount EarnHistory => '/'
  mount Profilelist => '/'

  root "matches#index"

  get "dashboard/index"

  get "players", to: "teams#players"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :withdrawls, dependent: :destroy
  has_many :points, dependent: :destroy
end

app/models/applist.rb
class Applist < ApplicationRecord
end

app/models/appopen.rb
class Appopen < ApplicationRecord
  belongs_to :user
end

app/models/game_point.rb
class GamePoint < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
end 

app/models/point.rb
class Point < ApplicationRecord
    belongs_to :account
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
    has_many :news
end

app/models/user.rb
class User < ApplicationRecord
    has_many :appopens, dependent: :destroy
    has_one :account, dependent: :destroy
    has_one :user_profile, dependent: :destroy
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/models/withdrawl.rb
class Withdrawl < ApplicationRecord
  belongs_to :account
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:title, :short_title, :views, :is_live, :status, :front_team, :opp_team)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :short_title, style: "display: block" %>
    <%= form.text_field :short_title %>
  </div>

  <div>
    <%= form.label :views, style: "display: block" %>
    <%= form.number_field :views %>
  </div>

  <div>
    <%= form.label :is_live, style: "display: block" %>
    <%= form.check_box :is_live %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :front_team, style: "display: block" %>
    <%= form.text_field :front_team %>
  </div>

  <div>
    <%= form.label :opp_team, style: "display: block" %>
    <%= form.text_field :opp_team %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<!-- <div id="<%= dom_id match %>">
  <p>
    <strong>Title:</strong>
    <%= match.title %>
  </p>

  <p>
    <strong>Short title:</strong>
    <%= match.short_title %>
  </p>

  <p>
    <strong>Views:</strong>
    <%= match.views %>
  </p>

  <p>
    <strong>Is live:</strong>
    <%= match.is_live %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= match.status %>
  </p>

  <p>
    <strong>Front team:</strong>
    <%= match.front_team %>
  </p>

  <p>
    <strong>Opp team:</strong>
    <%= match.opp_team %>
  </p>

</div> -->
  <td class="col"><%= match.title %></td>
  <td class="col"><%= match.short_title %></td>
  <td class="col"><%= match.views %></td>
  <td class="col"><%= match.is_live %></td>  
  <td class="col"><%= match.status %></td>  
  <td class="col"><%= match.front_team %></td>  
  <td class="col"><%= match.opp_team %></td>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  
<div class="d-flex justify-content-between align-items-center">
  <h1>Matches</h1>
  <%= link_to "New match", new_match_path , class: "btn btn-primary" %>
</div>

<table class="table table-info table-striped table-hover" style="text-align: center;">
  <thead>
    <tr>
    <th>Title</th>
    <th>Short_title</th>
    <th>Views</th>
    <th>Is_Live</th>
    <th>Status</th>
    <th>Front_team</th>
    <th>Opp_team</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
  </thead>
  <% @matches.each do |match| %>
  <tr>

    <%= render match %>
    
   <td> <%= link_to "Show this match", match, class: "btn btn-info" %></td>
   <td><%= link_to "Edit this match", edit_match_path(match), class: "btn btn-warning" %></td>
   <td><%= button_to "Destroy this match", @match, method: :delete, class: "btn btn-danger" %></td>
  </tr> 
  <% end %>
</table>
<div class="d-flex justify-content-between">
  <%= will_paginate @teams,renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <span><%= page_entries_info(@teams)%></span>
</div>
</div>

app/views/matches/new.html.erb
<div class="container-fluid">
    <h1>New match</h1>
    <%= render "form", match: @match %>
    <br>
      <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<div class="container-fluid">
<p style="color: green"><%= notice %></p>
<table class="table table-dark table-striped table-hover">
  <thead>
    <tr>
    <th>Title</th>
    <th>Short_title</th>
    <th>Views</th>
    <th>Is_Live</th>
    <th>Status</th>
    <th>Front_team</th>
    <th>Opp_team</th>
    <th>Edit</th>
    <th>Show</th>
    <th>Destroy</th>

    </tr>
  </thead>
  <tr>
   <%= render @match %>

  <td><%= link_to "Edit this match", edit_match_path(@match) %></td>
  <td><%= link_to "Back to matches", matches_path %></td>

  <td><%= button_to "Destroy this match", @match, method: :delete %></td>
  </tr>
</table>
</div>